DATASET:
  # path: /home/bulgogi/bolero/dataset/mnist_png/training/5
  path: /Users/bolero/dc/dataset/mnist_png/mnist_png/training/**
  img_size: [28, 28]

TRAIN:
  lr: 0.00001
  epochs: 4
  batch_size: 1
